name: bild-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        node: ['16']
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run lint